# /website/_config.yml
title: IntelliFlow
description: Intelligent Automated Cloud Migraitons & DR Solution
baseurl: "/website"
url: "https://chasenaquin.github.io/jekyll-test/#" # Replace with your GitHub Pages URL
theme: minima
permalink: pretty

# Docs collection
collections:
  docs:
    output: true
    permalink: /docs/:path/

# Defaults for docs
defaults:
  - scope:
      path: ""
      type: docs
    values:
      layout: default

# Include assets to ensure theyâ€™re copied to _site
include:
  - assets

# Exclude unnecessary files from the build
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - .sass-cache
  - .jekyll-cache
  - .gitignore
