title: ELT Awesome Docs
description: Modern documentation for ELT's projects
domain: "https://github.com/chasenaquin/jekyll-test"
url: "https://chasenaquin.github.io"
baseurl: "/jekyll-test"
#theme: minima
remote_theme: pmarsceill/just-the-docs
remote_theme_assets: true
permalink: pretty
collections:
  docs:
    output: true
    permalink: /docs/:path/
defaults:
  - scope:
      path: ""
      type: docs
    values:
      layout: default
include:
  - website
keep_files:
  - website/assets
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - .sass-cache
  - .jekyll-cache
  - .gitignore
